services:
  postgres:
    image: postgres:15
    container_name: fraud_sharing_db
    environment:
      POSTGRES_DB: fraud_sharing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
