"""initial schema v2: source_type, claim_type, no confirmed/confidence

Revision ID: 1c1e94e65770
Revises: 
Create Date: 2026-02-27 14:02:55.188790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c1e94e65770'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('rate_limit', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('candidate_uid', sa.UUID(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_table('candidates',
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('hh_id_hash', sa.String(), nullable=True),
    sa.Column('phone_hash', sa.String(), nullable=True),
    sa.Column('email_hash', sa.String(), nullable=True),
    sa.Column('name_dob_hash', sa.String(), nullable=True),
    sa.Column('fullname_dob_hash', sa.String(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=True),
    sa.Column('consent_obtained', sa.Boolean(), nullable=True),
    sa.Column('consent_source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_candidates_email_hash'), 'candidates', ['email_hash'], unique=False)
    op.create_index(op.f('ix_candidates_fullname_dob_hash'), 'candidates', ['fullname_dob_hash'], unique=False)
    op.create_index(op.f('ix_candidates_hh_id_hash'), 'candidates', ['hh_id_hash'], unique=True)
    op.create_index(op.f('ix_candidates_name_dob_hash'), 'candidates', ['name_dob_hash'], unique=False)
    op.create_index(op.f('ix_candidates_phone_hash'), 'candidates', ['phone_hash'], unique=False)
    op.create_table('candidate_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('claim_type', sa.String(), nullable=False),
    sa.Column('client_uid', sa.String(), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('worked_from', sa.String(), nullable=True),
    sa.Column('worked_to', sa.String(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['candidates.uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'client_uid', 'company', name='uq_source_client_company')
    )
    op.create_index('idx_sources_company', 'candidate_sources', ['company'], unique=False)
    op.create_index('idx_sources_source_id', 'candidate_sources', ['source_id'], unique=False)
    op.create_index('idx_sources_uid', 'candidate_sources', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sources_uid', table_name='candidate_sources')
    op.drop_index('idx_sources_source_id', table_name='candidate_sources')
    op.drop_index('idx_sources_company', table_name='candidate_sources')
    op.drop_table('candidate_sources')
    op.drop_index(op.f('ix_candidates_phone_hash'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_name_dob_hash'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_hh_id_hash'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_fullname_dob_hash'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_email_hash'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
